# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AdvancedInteraction`.
# Please instead update this file by running `bin/tapioca dsl AdvancedInteraction`.

class AdvancedInteraction
  sig { returns(T.untyped) }
  def cow; end

  sig { params(value: T.untyped).void }
  def cow=(value); end
end
