# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SayHello`.
# Please instead update this file by running `bin/tapioca dsl SayHello`.

class SayHello
  sig { returns(T.untyped) }
  def name; end

  sig { params(value: T.untyped).void }
  def name=(value); end
end
